from typing import Any

class BindingErrors:
    errors: list[Any]
    is_binding_errors: bool

    def __init__(self, errors: list[Any]) -> None: ...

class BindingEngine:
    def __init__(self, options: dict[str, Any]) -> None: ...
    async def get_settings(self) -> Any: ...
    async def get_session(self) -> Any: ...
    async def get_schema(self) -> Any: ...
    async def list_repositories(self) -> Any: ...
    async def index_repository(self, input: dict[str, Any]) -> Any: ...
    async def list_projects(self, input: dict[str, Any]) -> Any: ...
    async def write_graph(self, input: dict[str, Any]) -> Any: ...
    async def read_graph(self, input: dict[str, Any]) -> Any: ...
    async def query_graph(self, input: dict[str, Any]) -> Any: ...
    async def search_graph(self, input: dict[str, Any]) -> Any: ...
    async def trace_graph(self, input: dict[str, Any]) -> Any: ...
    async def export_okf(self, input: dict[str, Any]) -> Any: ...
    async def close(self) -> None: ...
    @property
    def is_closed(self) -> bool: ...

class TraceSubscriberGuard:
    def close(self) -> None: ...

def create_tokio_runtime(blocking_threads: int | None = None) -> None: ...
def init_trace_subscriber() -> TraceSubscriberGuard | None: ...
