packages:
  - tools/*
  - bindings/*
  - docs/*
catalog:
  "@ls-lint/ls-lint": ^2.3.1
  "@nx/devkit": 23.0.2
  "@nx/eslint-plugin": 23.0.2
  "@nx/js": 23.0.2
  "@nx/plugin": 23.0.2
  "@nx/vite": 23.0.2
  "@nx/vitest": 23.0.2
  "@nx/workspace": 23.0.2
  "@emnapi/core": 1.11.2
  "@emnapi/runtime": 1.11.2
  "@powerlines/nx": ^0.13.182
  "@powerlines/tsconfig": ^0.4.191
  "@powerlines/tsdoc": ^0.2.139
  "@powerlines/plugin-napi-rs": ^0.2.196
  "@powerlines/plugin-tsdown": ^0.1.544
  "@storm-software/config": ^1.138.29
  "@storm-software/config-tools": ^1.190.92
  "@storm-software/cspell": ^0.46.160
  "@storm-software/eslint": ^0.170.126
  "@storm-software/eslint-plugin-tsdoc": ^0.0.55
  "@storm-software/git-tools": ^2.131.100
  "@storm-software/linting-tools": ^1.134.22
  "@storm-software/markdownlint": ^0.30.248
  "@storm-software/prettier": ^0.59.145
  "@storm-software/pnpm-tools": ^0.7.103
  "@storm-software/tsconfig": ^0.48.159
  "@storm-software/untyped": ^0.24.234
  "@storm-software/workspace-tools": ^1.296.72
  "@napi-rs/cli": ^3.7.2
  "@napi-rs/wasm-runtime": ^1.1.6
  "@types/node": ^25.9.5
  "@typescript/native-preview": 7.0.0-dev.20251218.3
  copyfiles: ^2.4.1
  eslint: ^10.7.0
  emnapi: 1.11.2
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  signal-exit: ^4.1.0
  nx: 23.0.2
  prettier: ^3.9.5
  powerlines: ^0.47.143
  jiti: ^2.7.0
  tsdown: ^0.22.5
  rimraf: ^6.1.3
  verdaccio: 6.0.5
  vite: ^8.1.4
  vitest: ~4.1.10
  zx: ^8.8.5
overrides:
  "@telepathic/tools-config": workspace:*
  "@telepathic/tools-scripts": workspace:*
  "@telepathic/tools-cspell": workspace:*
  "@telepathic/bindings": workspace:*
  cookie: ">=0.7.0"
  debug: ">=4.4.0"
  follow-redirects: ">=1.15.9"
  got: ">=14.4.5"
  ip: ">=2.0.1"
  loader-utils: ">=3.3.1"
  markdown-it: ">=14.1.0"
  micromatch: ">=4.0.8"
  node-fetch: ">=3.3.2"
  nth-check: ">=2.1.1"
  parse-path: ">=7.0.0"
  parse-url: ">=9.2.0"
  path-to-regexp: ">=0.1.12"
  postcss: ">=8.5.1"
  shell-quote: ">=1.8.2"
  simple-git: ">=3.27.0"
shamefullyHoist: true
fetchTimeout: 450000
dedupeDirectDeps: true
dedupePeerDependents: true
linkWorkspacePackages: true
catalogMode: prefer
cleanupUnusedCatalogs: true
minimumReleaseAge: 2160
minimumReleaseAgeExclude:
  - "@storm-software/*"
  - conventional-changelog-storm-software
  - "@stryke/*"
  - "@powerlines/*"
  - powerlines
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  core-js: true
  esbuild: true
  lefthook: true
  nx: true
  unrs-resolver: true
supportedArchitectures:
  cpu:
    - current
    - wasm32
