packages:
  - apps/*
  - tools/*
  - bindings/*
  - docs/*
catalog:
  "@ls-lint/ls-lint": ^2.3.1
  "@nx/devkit": 23.0.2
  "@nx/eslint-plugin": 23.0.2
  "@nx/js": 23.0.2
  "@nx/plugin": 23.0.2
  "@nx/vite": 23.0.2
  "@nx/vitest": 23.0.2
  "@nx/workspace": 23.0.2
  "@emnapi/core": 1.11.2
  "@emnapi/runtime": 1.11.2
  "@powerlines/nx": ^0.13.183
  "@powerlines/tsconfig": ^0.4.192
  "@powerlines/tsdoc": ^0.2.140
  "@powerlines/plugin-napi-rs": ^0.2.197
  "@powerlines/plugin-tsdown": ^0.1.545
  "@storm-software/config": ^1.138.44
  "@storm-software/config-tools": ^1.190.107
  "@storm-software/cspell": ^0.46.175
  "@storm-software/eslint": ^0.170.141
  "@storm-software/eslint-plugin-tsdoc": ^0.0.70
  "@storm-software/git-tools": ^2.131.115
  "@storm-software/linting-tools": ^1.134.37
  "@storm-software/markdownlint": ^0.30.263
  "@storm-software/prettier": ^0.59.160
  "@storm-software/pnpm-tools": ^0.7.118
  "@storm-software/tsconfig": ^0.48.174
  "@storm-software/untyped": ^0.24.249
  "@storm-software/workspace-tools": ^1.296.87
  "@napi-rs/cli": ^3.7.3
  "@napi-rs/wasm-runtime": ^1.1.6
  "@tauri-apps/api": ^2.11.1
  "@tauri-apps/cli": ^2.11.4
  "@tauri-apps/plugin-opener": ^2.5.4
  "@types/node": ^25.9.5
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  "@typescript/native-preview": 7.0.0-dev.20251218.3
  "@vitejs/plugin-react": ^4.7.0
  copyfiles: ^2.4.1
  eslint: ^10.7.0
  emnapi: 1.11.2
  lefthook: ^1.13.6
  log4brains: ^1.1.0
  react: ^19.2.7
  react-dom: ^19.2.7
  signal-exit: ^4.1.0
  nx: 23.0.2
  prettier: ^3.9.5
  powerlines: ^0.47.144
  jiti: ^2.7.0
  tsdown: ^0.22.8
  rimraf: ^6.1.3
  verdaccio: 6.0.5
  vite: ^8.1.4
  vitest: ~4.1.10
  zx: ^8.8.5
overrides:
  "@telepathic/tools-config": workspace:*
  "@telepathic/tools-scripts": workspace:*
  "@telepathic/tools-cspell": workspace:*
  "@telepathic/bindings": workspace:*
  cookie: ">=0.7.0"
  debug: ">=4.4.0"
  follow-redirects: ">=1.15.9"
  got: ">=14.4.5"
  ip: ">=2.0.1"
  loader-utils: ">=3.3.1"
  markdown-it: ">=14.1.0"
  micromatch: ">=4.0.8"
  node-fetch: ">=3.3.2"
  nth-check: ">=2.1.1"
  parse-path: ">=7.0.0"
  parse-url: ">=9.2.0"
  path-to-regexp: ">=0.1.12"
  postcss: ">=8.5.1"
  shell-quote: ">=1.8.2"
  simple-git: ">=3.27.0"
shamefullyHoist: true
fetchTimeout: 450000
dedupeDirectDeps: true
dedupePeerDependents: true
linkWorkspacePackages: true
catalogMode: prefer
cleanupUnusedCatalogs: true
minimumReleaseAge: 2160
minimumReleaseAgeExclude:
  - "@storm-software/*"
  - conventional-changelog-storm-software
  - "@stryke/*"
  - "@powerlines/*"
  - powerlines
  - "@microsoft/api-extractor-model@7.33.9"
  - "@microsoft/api-extractor@7.58.10"
  - "@rushstack/node-core-library@5.23.2"
  - "@rushstack/terminal@0.24.1"
  - "@rushstack/ts-command-line@5.3.11"
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  core-js: true
  esbuild: true
  lefthook: true
  nx: true
  unrs-resolver: true
supportedArchitectures:
  cpu:
    - current
    - wasm32
