name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: override release tag
        required: false
  push:
    branches:
      - main
      - next
      - experimental

env:
  CI: true
  DEBUG: napi:*
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  CARGO_INCREMENTAL: "1"
  STORM_REPOSITORY: ${{ github.repositoryUrl }}
  STORM_WORKSPACE_ROOT: ${{ github.workspace }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_TOKEN: ${{ github.token }}
  NPM_TOKEN: ${{ secrets.STORM_BOT_NPM_TOKEN }}

jobs:
  start:
    name: Send in progress notification
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    if: github.repository == 'storm-software/telepathic' && (github.ref ==
      'refs/heads/main' || github.ref == 'refs/heads/next' || github.ref ==
      'refs/heads/experimental')
    steps:
      - name: Send notification - Deployment started
        uses: storm-software/action-notify@main
        with:
          title: "Deployment for ${{ github.repository }} has started (In Progress)"
          subtitle: "Deployment for ${{ github.repository }} has started - #${{
            github.run_number }}"
          description:
            "Deployment for ${{ github.repository }} is currently in progress -
            #${{ github.run_number }}. Click here to view the changes associated
            with this deployment: ${{ github.event.pull_request.html_url ||
            github.event.head_commit.url }} "
          color: 2077350
          status: In Progress
          slack-token: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
          telegram-token: ${{ secrets.STORM_BOT_TELEGRAM_TOKEN }}
          telegram-chat: ${{ secrets.STORM_BOT_TELEGRAM_NOTIFICATION_CHAT }}
          discord-webhook: ${{ secrets.STORM_BOT_DISCORD_WEBHOOK}}

  build-bindings:
    name: Build bindings - ${{ matrix.target }}
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') &&
      github.event.pull_request.draft == false
    runs-on: ${{ matrix.host }}
    environment: production
    permissions:
      contents: write
      id-token: write
    needs:
      - start
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS
          - host: macos-latest
            target: x86_64-apple-darwin
            profile: release-darwin-x86_64
          - host: macos-latest
            target: aarch64-apple-darwin
            profile: release-darwin

          # Windows MSVC
          - host: ubuntu-latest
            target: x86_64-pc-windows-msvc
            profile: release-windows-x86_64
          - host: ubuntu-latest
            target: aarch64-pc-windows-msvc
            profile: release-windows-aarch64
          - host: ubuntu-latest
            target: i686-pc-windows-msvc
            profile: release-windows-i686

          # Linux (x86_64)
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            profile: release-linux-gnu-x86_64
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            profile: release-linux-musl-x86_64

          # Linux (aarch64)
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            profile: release-linux-gnu-aarch64
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            profile: release-linux-musl-aarch64

          # Linux (armv7)
          - host: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            profile: release-linux-gnueabihf-armv7

          # Linux (Android)
          - host: ubuntu-latest
            target: aarch64-linux-android
            profile: release-linux-android-aarch64
          - host: ubuntu-latest
            target: armv7-linux-androideabi
            profile: release-linux-android-armv7

          # WebAssembly
          - host: ubuntu-latest
            target: wasm32-wasip1-threads
            profile: release-wasm32-wasip1

          # FreeBSD
          - host: ubuntu-latest
            target: x86_64-unknown-freebsd
            profile: release-freebsd-x86_64
    steps:
      - name: Setup workspace
        uses: storm-software/action-devenv-setup@main
        with:
          gpg-sign-key: ${{ secrets.STORM_BOT_GPG_SIGN_KEY }}
          gpg-private-key: ${{ secrets.STORM_BOT_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.STORM_BOT_GPG_PASSPHRASE }}
          storm-bot-github-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.STORM_BOT_CACHIX_AUTH_TOKEN }}

      - name: Build native binding
        run: devenv --profile ${{ matrix.profile }} --no-tui --impure shell build-native ${{ matrix.target }}
        env:
          NATIVE_TARGET: ${{ matrix.target }}
          NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1
          CACHIX_AUTH_TOKEN: ${{ secrets.STORM_BOT_CACHIX_AUTH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.STORM_BOT_RUSTC_CACHE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STORM_BOT_RUSTC_CACHE_SECRET_ACCESS_KEY }}

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.6.2
        if: matrix.target != 'wasm32-wasip1-threads'
        with:
          name: bindings-${{ matrix.target }}
          path: packages/base/bindings/artifacts/*.node
          if-no-files-found: error

      - name: Upload artifact - WASM
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.6.2
        if: matrix.target == 'wasm32-wasip1-threads'
        with:
          name: bindings-${{ matrix.target }}
          path: packages/base/bindings/artifacts/*.wasm
          if-no-files-found: error

  release:
    name: Release
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    needs:
      - start
      - build-bindings
    steps:
      - name: Setup workspace
        uses: storm-software/action-devenv-setup@main
        with:
          gpg-sign-key: ${{ secrets.STORM_BOT_GPG_SIGN_KEY }}
          gpg-private-key: ${{ secrets.STORM_BOT_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.STORM_BOT_GPG_PASSPHRASE }}
          storm-bot-github-token: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.STORM_BOT_CACHIX_AUTH_TOKEN }}

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0
        with:
          main-branch-name: main
          workflow-id: release.yml
          set-environment-variables-for-job: true
          error-on-no-successful-workflow: false

      - name: Download binding artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: packages/base/bindings/artifacts
          pattern: bindings-*
          merge-multiple: true

      - name: Release repository updates
        run: devenv --profile release --no-tui shell release ${{
          steps.setSHAs.outputs.base }} ${{ steps.setSHAs.outputs.head }}
        env:
          NX_BASE: ${{ steps.setSHAs.outputs.base }}
          NX_HEAD: ${{ steps.setSHAs.outputs.head }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
          STORM_BOT_GITHUB_TOKEN: ${{ secrets.STORM_BOT_GITHUB_TOKEN }}
          STORM_WORKSPACE_ROOT: ${{ github.workspace }}
          STORM_REPOSITORY: ${{ github.repositoryUrl }}
          NPM_TOKEN: ${{ secrets.STORM_BOT_NPM_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.STORM_BOT_CLOUDFLARE_TOKEN }}
          CACHIX_AUTH_TOKEN: ${{ secrets.STORM_BOT_CACHIX_AUTH_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.STORM_BOT_RUSTC_CACHE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STORM_BOT_RUSTC_CACHE_SECRET_ACCESS_KEY }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.STORM_BOT_CARGO_TOKEN }}
          TAG: ${{ inputs.tag }}

  success:
    needs:
      - release
    if: ${{ success() }}
    name: Send success notification
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Send notification - Deployment successful
        uses: storm-software/action-notify@main
        with:
          title: "Deployment for ${{ github.repository }} has finished (Success)"
          subtitle:
            "Deployment for ${{ github.repository }} has finished successfully -
            #${{ github.run_number }}"
          description:
            "Deployment for ${{ github.repository }} has finished successfully
            - #${{ github.run_number }}. Click here to view the changes
            associated with this deployment: ${{
            github.event.pull_request.html_url || github.event.head_commit.url
            }} "
          color: 556891
          status: Success
          slack-token: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
          telegram-token: ${{ secrets.STORM_BOT_TELEGRAM_TOKEN }}
          telegram-chat: ${{ secrets.STORM_BOT_TELEGRAM_NOTIFICATION_CHAT }}
          discord-webhook: ${{ secrets.STORM_BOT_DISCORD_WEBHOOK}}

  failure:
    needs:
      - release
    if: ${{ failure() }}
    name: Send failure notification
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Send notification - Deployment failed
        uses: storm-software/action-notify@main
        with:
          title: "Deployment for ${{ github.repository }} has finished (Failure)"
          subtitle:
            "Deployment for ${{ github.repository }} finished with failures - #${{
            github.run_number }}"
          description:
            "Deployment for ${{ github.repository }} finished with failures -
            #${{ github.run_number }}. Click here to view the changes associated
            with this deployment: ${{ github.event.pull_request.html_url ||
            github.event.head_commit.url }} "
          color: 10027008
          status: Failure
          slack-token: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
          telegram-token: ${{ secrets.STORM_BOT_TELEGRAM_TOKEN }}
          telegram-chat: ${{ secrets.STORM_BOT_TELEGRAM_NOTIFICATION_CHAT }}
          discord-webhook: ${{ secrets.STORM_BOT_DISCORD_WEBHOOK}}

  cancelled:
    needs:
      - release
    if: ${{ cancelled() }}
    name: Send cancelled notification
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Send notification - Deployment cancelled
        uses: storm-software/action-notify@main
        with:
          title: "Deployment for ${{ github.repository }} has finished (Cancelled)"
          subtitle:
            "Deployment for ${{ github.repository }} has been cancelled - #${{
            github.run_number }}"
          description:
            "Deployment for ${{ github.repository }} was stopped before it
            could complete - #${{ github.run_number }}. Click here to view the
            changes associated with this deployment: ${{
            github.event.pull_request.html_url || github.event.head_commit.url
            }}."
          color: 16565273
          status: Cancelled
          slack-token: ${{ secrets.STORM_BOT_SLACK_TOKEN }}
          telegram-token: ${{ secrets.STORM_BOT_TELEGRAM_TOKEN }}
          telegram-chat: ${{ secrets.STORM_BOT_TELEGRAM_NOTIFICATION_CHAT }}
          discord-webhook: ${{ secrets.STORM_BOT_DISCORD_WEBHOOK}}
